<?php
if (function_exists('pll_register_string')) {
    pll_register_string('pointer_theme', 'Также вам понравится');
    pll_register_string('pointer_theme', 'Подобные экскурсии');
    pll_register_string('pointer_theme', 'Все');
    pll_register_string('pointer_theme', 'Назад к блогу');
    pll_register_string('pointer_theme', 'Назад к эскурсиям');
    pll_register_string('pointer_theme', 'Такая страница отсутствует');
    pll_register_string('pointer_theme', 'Назад к главной странице');
    pll_register_string('pointer_theme', 'Показать все фото');
    pll_register_string('pointer_theme', 'Добавить отзыв');
    pll_register_string('pointer_theme', 'Смотреть видео');
    pll_register_string('pointer_theme', 'Заказать тур');
    pll_register_string('pointer_theme', 'Сортировать');
    pll_register_string('pointer_theme', 'Популярные');
    pll_register_string('pointer_theme', 'Новые');
    pll_register_string('pointer_theme', 'От А-Я');
    pll_register_string('pointer_theme', 'Дата');
    pll_register_string('pointer_theme', 'Твоя Корзина');
    pll_register_string('pointer_theme', 'Оформить заказ');
    pll_register_string('pointer_theme', 'Продолжить покупки');
    pll_register_string('pointer_theme', 'Корзина пустая');
    pll_register_string('pointer_theme', 'Найти экскурсию');
    pll_register_string('pointer_theme', 'Екскурсії не знайдені');
    pll_register_string('pointer_theme', 'Статті не знайдені');
    pll_register_string('pointer_theme', 'ФИЛЬТРЫ');
    pll_register_string('pointer_theme', 'Тип экскурсии');
    pll_register_string('pointer_theme', 'Очистить');
    pll_register_string('pointer_theme', 'По цене');
    pll_register_string('pointer_theme', 'Выбор города');
    pll_register_string('pointer_theme', 'Ваш заказ');
    pll_register_string('pointer_theme', 'Данные покупателя');
    pll_register_string('pointer_theme', 'Дополнительная информация');
    pll_register_string('pointer_theme', 'Отправить заказ');
    pll_register_string('pointer_theme', 'Все результаты');
    pll_register_string('pointer_theme', 'Результатов');
    pll_register_string('pointer_theme', 'Экскурсии');
    pll_register_string('pointer_theme', 'Экскурсия');
    pll_register_string('pointer_theme', 'Блог');
    pll_register_string('pointer_theme', 'Заголовок удачного поиска');
    pll_register_string('pointer_theme', 'Заголовок не удачного поиска');
}
